In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
from combine_jsons import *

In [2]:
df1 = pd.read_csv('data/PMI_Res_Transaction_w_STN.csv')
df1['Date'] = pd.to_datetime(df1['Date']).dt.normalize()
df1.head(3)

,area,contractDate,district,floorRange,marketSegment,nettPrice,noOfUnits,price,project,propertyType,...,date_ingested,Lat,Lon,STN_NAME,STN_NO,STN_SVY21_X,STN_SVY21_Y,STN_Lat,STN_Lon,Project_to_STN_dist
0,93.0,616,14,06-10,RCR,93.0,1,1100000.0,# 1 LOFT,Apartment,...,210322,1.320021,103.876308,ALJUNIED MRT STATION,EW9,33518.6049,33190.002,1.319404,103.879953,0.411408
1,52.0,617,14,06-10,RCR,52.0,1,600000.0,# 1 LOFT,Apartment,...,210322,1.320021,103.876308,ALJUNIED MRT STATION,EW9,33518.6049,33190.002,1.319404,103.879953,0.411408
2,52.0,917,14,06-10,RCR,52.0,1,615000.0,# 1 LOFT,Apartment,...,210322,1.320021,103.876308,ALJUNIED MRT STATION,EW9,33518.6049,33190.002,1.319404,103.879953,0.411408

In [3]:
df2 = combine_and_preprocess_jsons()

Found 5 JSON files to process.
2026-01-07 12:38:48.431154 :	 Working on jsons/20251230-1.json

2026-01-07 12:38:48.431870 :	 Working on jsons/20251230-2.json

2026-01-07 12:38:48.432275 :	 Working on jsons/20251230-3.json

2026-01-07 12:38:48.432641 :	 Working on jsons/20251230-4.json

2026-01-07 12:38:48.476375 :	 Working on jsons/20251230-2-cleaned.json

2026-01-07 12:38:53.188009 :	 jsons/20251230-1.json completed.

2026-01-07 12:38:56.287148 :	 jsons/20251230-4.json completed.

2026-01-07 12:39:01.930127 :	 jsons/20251230-2-cleaned.json completed.

2026-01-07 12:39:02.077006 :	 jsons/20251230-2.json completed.

2026-01-07 12:39:06.589201 :	 jsons/20251230-3.json completed.

In [4]:
df2

,area,contractDate,district,floorRange,marketSegment,nettPrice,noOfUnits,price,project,propertyType,...,x,y,cleanTenure,startYear,Age,remainingLease,psm,psf,Date,sqft
0,186.0,0321,05,-,RCR,NaN,1,1880000.0,LANDED HOUSING DEVELOPMENT,Strata Terrace,...,20914.1988965525,30589.1070785135,1000,1000,0,1000,10107.526882,939.012159,2021-03-01,2002.1040
1,257.0,0522,05,-,RCR,NaN,1,4600000.0,LANDED HOUSING DEVELOPMENT,Terrace,...,20914.1988965525,30589.1070785135,1000,1000,0,1000,17898.832685,1662.842130,2022-05-01,2766.3480
2,308.0,0921,05,-,RCR,NaN,1,5200000.0,LANDED HOUSING DEVELOPMENT,Semi-detached,...,NaN,NaN,1000,1000,0,1000,16883.116883,1568.479829,2021-09-01,3315.3120
3,228.4,0724,05,-,RCR,NaN,1,5188888.0,LANDED HOUSING DEVELOPMENT,Semi-detached,...,NaN,NaN,1000,1000,0,1000,22718.423818,2110.593071,2024-07-01,2458.4976
4,59.0,1025,07,06-10,CCR,NaN,1,1777000.0,AUREA,Apartment,...,NaN,NaN,99,2024,-3,102,30118.644068,2798.090307,2025-10-01,635.0760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133910,129.0,0425,19,01-05,OCR,NaN,1,1548000.0,PRIVE,Executive Condominium,...,35969.63449,42560.406,99,2010,11,88,12000.000000,1114.827202,2025-04-01,1388.5560
133911,82.0,0425,19,11-15,OCR,NaN,1,1358888.0,PRIVE,Executive Condominium,...,35969.63449,42560.406,99,2010,11,88,16571.804878,1539.558238,2025-04-01,882.6480
133912,98.0,0425,19,16-20,OCR,NaN,1,1738000.0,PRIVE,Executive Condominium,...,35969.63449,42560.406,99,2010,11,88,17734.693878,1647.593263,2025-04-01,1054.8720
133913,78.0,1225,15,01-05,OCR,NaN,1,1290000.0,RESIDENCE 118,Apartment,...,36988.73873,32708.62403,1000,1000,0,1000,16538.461538,1536.460567,2025-12-01,839.5920
133914,76.0,0523,15,01-05,OCR,NaN,1,1100000.0,RESIDENCE 118,Apartment,...,36988.73873,32708.62403,1000,1000,0,1000,14473.684211,1344.638072,2023-05-01,818.0640

In [5]:
df = concatenate_dataframes(df1, df2)
df

,area,contractDate,district,floorRange,marketSegment,nettPrice,noOfUnits,price,project,propertyType,...,x,y,cleanTenure,startYear,Age,remainingLease,psm,psf,Date,sqft
0,93.0,616,14,06-10,RCR,93.0,1,1100000.0,# 1 LOFT,Apartment,...,33586.81522,32784.28772,1000,1000,0,1000,11827.960000,1098.840000,2016-06-01,1001.000
1,52.0,617,14,06-10,RCR,52.0,1,600000.0,# 1 LOFT,Apartment,...,33586.81522,32784.28772,1000,1000,0,1000,11538.460000,1071.950000,2017-06-01,560.000
2,52.0,917,14,06-10,RCR,52.0,1,615000.0,# 1 LOFT,Apartment,...,33586.81522,32784.28772,1000,1000,0,1000,11826.920000,1098.750000,2017-09-01,560.000
3,123.0,1017,14,01-05,RCR,123.0,1,930000.0,# 1 LOFT,Apartment,...,33586.81522,32784.28772,1000,1000,0,1000,7560.980000,702.430000,2017-10-01,1324.000
4,52.0,1117,14,06-10,RCR,52.0,1,618000.0,# 1 LOFT,Apartment,...,33586.81522,32784.28772,1000,1000,0,1000,11884.620000,1104.110000,2017-11-01,560.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314802,129.0,0425,19,01-05,OCR,NaN,1,1548000.0,PRIVE,Executive Condominium,...,35969.63449,42560.406,99,2010,11,88,12000.000000,1114.827202,2025-04-01,1388.556
314803,82.0,0425,19,11-15,OCR,NaN,1,1358888.0,PRIVE,Executive Condominium,...,35969.63449,42560.406,99,2010,11,88,16571.804878,1539.558238,2025-04-01,882.648
314804,98.0,0425,19,16-20,OCR,NaN,1,1738000.0,PRIVE,Executive Condominium,...,35969.63449,42560.406,99,2010,11,88,17734.693878,1647.593263,2025-04-01,1054.872
314805,78.0,1225,15,01-05,OCR,NaN,1,1290000.0,RESIDENCE 118,Apartment,...,36988.73873,32708.62403,1000,1000,0,1000,16538.461538,1536.460567,2025-12-01,839.592
314806,76.0,0523,15,01-05,OCR,NaN,1,1100000.0,RESIDENCE 118,Apartment,...,36988.73873,32708.62403,1000,1000,0,1000,14473.684211,1344.638072,2023-05-01,818.064

In [6]:
print(df1.shape, df2.shape, df.shape)

(180892, 34) (133915, 24) (280936, 24)

In [7]:
def display_table(df):
    temp_df = df.sample(10)
    columns = df.columns
    i = 0
    for j in range(1, len(columns)//5+2):
        j *= 5
        display(temp_df[columns[i:j]])
        i = j

display_table(df)

         area contractDate district floorRange marketSegment
56426    71.0          620        9      26-30           CCR
40017    98.0          420       20      16-20           RCR
253235   41.0         0722       12      01-05           RCR
283081   83.0         0621       16      01-05           OCR
142091   99.0          721       18      01-05           OCR
146682   73.0          417       27      11-15           OCR
60981   115.0         1216       11      26-30           CCR
10494    87.0          721       20      11-15           RCR
62920    90.0         1016       27      01-05           OCR
254073   53.0         0223       09      21-25           CCR

,nettPrice,noOfUnits,price,project,propertyType
56426,71.0,1,2048000.0,MARTIN MODERN,Condominium
40017,98.0,1,1811000.0,JADESCAPE,Condominium
253235,NaN,1,728000.0,EIGHT RIVERSUITES,Condominium
283081,NaN,1,1050000.0,WATERFRONT GOLD,Condominium
142091,99.0,1,1270000.0,THE ALPS RESIDENCES,Condominium
146682,73.0,1,664000.0,THE CRITERION,Executive Condominium
60981,115.0,1,2350000.0,NEWTON SUITES,Apartment
10494,87.0,1,1170000.0,BISHAN POINT,Condominium
62920,90.0,1,1269000.0,NORTH PARK RESIDENCES,Apartment
254073,NaN,1,1255000.0,OUE TWIN PEAKS,Condominium

,street,tenure,typeOfArea,typeOfSale,x
56426,MARTIN PLACE,99 yrs lease commencing from 2016,Strata,1,28532.67705
40017,SHUNFU ROAD,99 yrs lease commencing from 2018,Strata,1,28554.17812
253235,WHAMPOA EAST,99 yrs lease commencing from 2011,Strata,3,31479.90364
283081,BEDOK RESERVOIR ROAD,99 yrs lease commencing from 2009,Strata,3,38594.31988
142091,TAMPINES STREET 86,99 yrs lease commencing from 2015,Strata,2,38727.87581
146682,YISHUN STREET 51,99 yrs lease commencing from 2014,Strata,1,29373.39049
60981,NEWTON ROAD,Freehold,Strata,3,29001.08103
10494,BRIGHT HILL DRIVE,99 yrs lease commencing from 1997,Strata,3,27930.26539
62920,YISHUN CENTRAL 1,99 yrs lease commencing from 2015,Strata,1,28390.14699
254073,LEONIE HILL ROAD,99 yrs lease commencing from 2010,Strata,3,28012.12948

                  y  cleanTenure  startYear  Age  remainingLease
56426   30653.80865           99       2016    5              94
40017   37102.33484           99       2018    3              96
253235  33732.08699           99       2011   10              89
283081  35560.66753           99       2009   12              87
142091  37414.33513           99       2015    6              93
146682  44502.85335           99       2014    7              92
60981   33341.24883         1000       1000    0            1000
10494   37969.74249           99       1997   24              75
62920   45560.43713           99       2015    6              93
254073  31280.89314           99       2010   11              88

                 psm          psf       Date      sqft
56426   28845.070000  2679.770000 2020-06-01   764.000
40017   18479.590000  1716.800000 2020-04-01  1055.000
253235  17756.097561  1649.581713 2022-07-01   441.324
283081  12650.602410  1175.269640 2021-06-01   893.412
142091  12828.280000  1191.780000 2021-07-01  1066.000
146682   9095.890000   845.030000 2017-04-01   786.000
60981   20434.780000  1898.440000 2016-12-01  1238.000
10494   13448.280000  1249.380000 2021-07-01   936.000
62920   14100.000000  1309.920000 2016-10-01   969.000
254073  23679.245283  2199.855563 2023-02-01   570.492

In [8]:
df[df['project'].str.contains("AVENUE SOUTH")]

,area,contractDate,district,floorRange,marketSegment,nettPrice,noOfUnits,price,project,propertyType,...,x,y,cleanTenure,startYear,Age,remainingLease,psm,psf,Date,sqft
6800,139.0,919,3,36-40,RCR,139.0,1,3206000.0,AVENUE SOUTH RESIDENCE,Apartment,...,27597.65868,28801.89427,99,2018,3,96,23064.750000,2142.770000,2019-09-01,1496.000
6801,67.0,919,3,21-25,RCR,67.0,1,1529000.0,AVENUE SOUTH RESIDENCE,Apartment,...,27597.65868,28801.89427,99,2018,3,96,22820.900000,2120.110000,2019-09-01,721.000
6802,68.0,919,3,16-20,RCR,68.0,1,1446000.0,AVENUE SOUTH RESIDENCE,Apartment,...,27597.65868,28801.89427,99,2018,3,96,21264.710000,1975.540000,2019-09-01,732.000
6803,68.0,919,3,16-20,RCR,68.0,1,1441000.0,AVENUE SOUTH RESIDENCE,Apartment,...,27597.65868,28801.89427,99,2018,3,96,21191.180000,1968.710000,2019-09-01,732.000
6804,68.0,919,3,16-20,RCR,68.0,1,1459000.0,AVENUE SOUTH RESIDENCE,Apartment,...,27597.65868,28801.89427,99,2018,3,96,21455.880000,1993.300000,2019-09-01,732.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189923,103.0,0425,03,11-15,RCR,NaN,1,2470000.0,AVENUE SOUTH RESIDENCE,Apartment,...,27597.65868,28801.89427,99,2018,3,96,23980.582524,2227.850476,2025-04-01,1108.692
189924,103.0,0625,03,01-05,RCR,NaN,1,2380000.0,AVENUE SOUTH RESIDENCE,Apartment,...,27597.65868,28801.89427,99,2018,3,96,23106.796117,2146.673738,2025-06-01,1108.692
189925,49.0,0425,03,16-20,RCR,NaN,1,1200000.0,AVENUE SOUTH RESIDENCE,Apartment,...,27597.65868,28801.89427,99,2018,3,96,24489.795918,2275.157555,2025-04-01,527.436
189926,68.0,0525,03,06-10,RCR,NaN,1,1510000.0,AVENUE SOUTH RESIDENCE,Apartment,...,27597.65868,28801.89427,99,2018,3,96,22205.882353,2062.976807,2025-05-01,731.952
189927,68.0,0525,03,16-20,RCR,NaN,1,1670000.0,AVENUE SOUTH RESIDENCE,Apartment,...,27597.65868,28801.89427,99,2018,3,96,24558.823529,2281.570376,2025-05-01,731.952

In [ ]:
df.sort_values(['Date', 'project', 'floorRange', 'area']).to_csv('data/PMI_Res_Transactions_20251230.csv', index=False)

In [10]:
df.columns

Index(['area', 'contractDate', 'district', 'floorRange', 'marketSegment',
       'nettPrice', 'noOfUnits', 'price', 'project', 'propertyType', 'street',
       'tenure', 'typeOfArea', 'typeOfSale', 'x', 'y', 'cleanTenure',
       'startYear', 'Age', 'remainingLease', 'psm', 'psf', 'Date', 'sqft'],
      dtype='object')

In [14]:
sorted(df['floorRange'].unique())

['-',
 '01-05',
 '06-10',
 '11-15',
 '16-20',
 '21-25',
 '26-30',
 '31-35',
 '36-40',
 '41-45',
 '46-50',
 '51-55',
 '56-60',
 '61-65',
 '66-70',
 '71-75',
 'B1-B5']

In [1]:
import pandas as pd
df = pd.read_csv('data/ResaleflatpricesJan2017onwards-20260107.csv')
df

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,250000.0
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,262000.0
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,265000.0
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,265000.0
...,...,...,...,...,...,...,...,...,...,...,...
222462,2026-01,YISHUN,4 ROOM,479C,YISHUN ST 42,04 TO 06,93.0,Model A,2021,94 years 04 months,608000.0
222463,2026-01,YISHUN,4 ROOM,478B,YISHUN ST 44,07 TO 09,93.0,Model A,2021,94 years 01 month,608000.0
222464,2026-01,YISHUN,4 ROOM,754,YISHUN ST 72,10 TO 12,84.0,Simplified,1985,58 years 09 months,490000.0
222465,2026-01,YISHUN,5 ROOM,419,YISHUN AVE 11,07 TO 09,122.0,Improved,1993,66 years 02 months,715000.0
222466,2026-01,YISHUN,5 ROOM,318C,YISHUN AVE 9,04 TO 06,112.0,Improved,2015,88 years 10 months,726000.0

In [5]:
df2 = pd.read_csv("artifacts/flat_details.csv")
df2.head()

,town,block,street_name,flat_model,lease_commence_date,flat_type,storey_range
0,ANG MO KIO,406,ANG MO KIO AVE 10,Improved,1979,2 ROOM,10 TO 12
1,ANG MO KIO,108,ANG MO KIO AVE 4,New Generation,1978,3 ROOM,01 TO 03
2,ANG MO KIO,602,ANG MO KIO AVE 5,New Generation,1980,3 ROOM,01 TO 03
3,ANG MO KIO,465,ANG MO KIO AVE 10,New Generation,1980,3 ROOM,04 TO 06
4,ANG MO KIO,601,ANG MO KIO AVE 5,New Generation,1980,3 ROOM,01 TO 03

In [20]:
df.loc[(df['town'] == "ANG MO KIO") \
        & (df['street_name'] == "ANG MO KIO AVE 1") \
        & (df['block'] == "310B") \
        & (df['flat_type'] == "4 ROOM") \
        & (df['storey_range'] == '01 TO 03')
        # 'block'].unique()
        ]

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
169451,2024-04,ANG MO KIO,4 ROOM,310B,ANG MO KIO AVE 1,01 TO 03,94.0,Model A,2012,87 years 06 months,800000.0

In [4]:
flat_details_cols = ['town', 'block', 'street_name', 'flat_model', 'lease_commence_date', 'flat_type', 'storey_range']
# We drop duplicates across all identifying columns to create a clean lookup table.
flat_details_df = df[flat_details_cols].drop_duplicates(subset=flat_details_cols).reset_index(drop=True)
flat_details_df.to_csv('artifacts/flat_details.csv', index=False)